### ISSUE TITLE
Large swathes of code are not compatible with Python 3

### ISSUE THREAD

**Issue by ross-spencer** [exponential-decay/demystify#42]
https://pythonclock.org/

**Comment by joshuatj** [comment]
Awesome! Thanks!

**Comment by ross-spencer** [comment]
I feel like the Python 3 notes were added to #46 in error, those are in that ticket and this [google doc](https://docs.google.com/document/d/1kfhpqUKN3zAToC2_gdYMaZ0QYu641VjziycnfpVf5i8/edit# not ) forgotten, just misplaced.

**Comment by ross-spencer** [comment]
TODO:

* [ ] Code marked `# TODO PY3`.

**Comment by ross-spencer** [comment]
Filter: https://github.com/exponential-decay/demystify/issues?q=is%3Aopen+is%3Aissue+label%3Apython-3

**Comment by ross-spencer** [comment]
There is a Python 3 release here: https://github.com/exponential-decay/demystify/releases/tag/v1.0.0

And a discussion about next steps here, with Packaging likely to be the next most important thing, with `sqliteid` to be packaged first: https://github.com/exponential-decay/demystify/discussions/68

@joshuatj if you happen to have time to give the new version a whirl, it'd be a great help if you managed to turn up any issues. Anyone else following along is welcome to give it a whirl too. 

Closing this issue now, ceremoniously. If there are issues with the new release, separate new issues would most helpful.
